version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timesheet-app
    ports:
      - "8005:80"
    volumes:
      - .:/var/www/html


    restart: unless-stopped
